---
title: "Baseline Data: Demographics Means and Standard Deviations"
output: 
  html_document:
    toc: yes
    number_sections: no
    theme: spacelab
    self_contained: no
---

```{r, echo=FALSE, warning=FALSE, message=FALSE}
#loading necessary packages, functions, and data
source("/git_repositories/bangla/scripts/load_packages.R")
baseline <- readRDS("~/Dropbox/Bangladesh Projects/Factories _ EWP/Data/baseline/in_process_data/cleaned_baseline.RDS")
```

#means and SDs
```{r, echo=FALSE}
baseline_mSD <- select(baseline, 
                       gender, sex, religion = dreligion, children = dchild, child_stay = dchild_stay, married = dmarried, 
                       live_spouse = dlive_sp, family_dep_food = dmem_dep_food, family_dep_income = dmem_dep_fin, 
                       education = dedu, write_bangla = dletterb, write_english = dlettere, years_anyGarment = dy_garment, 
                       years_currjob = dy_currjob, years_intendedFut = dy_exp, salary = salamount, income_spouse = dsp_inc, 
                       monthly_overtime = dinc_over, ladder_respect = dresp_comm, ladder_currStatus = dcurr_status, 
                       ladder_futStatus = dfut_status, ladder_pastStatus = dpast_status, factory, advice = dadvice)
stargazer(baseline_mSD)
```


```{r, eval=FALSE, echo=FALSE}
# > knit("b1_demographicsMsDs.Rmd")
```